openapi: 3.0.0
info:
  title: week22-milestone4-rpb
  version: 1.0.0
servers:
  - url: 'https://week22-rpb-s6tv3qk23q-uc.a.run.app'
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: auth
  - name: user
  - name: todo
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: rpb2
                password: rpb123
                role: user
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: rpb
                password: rpb123
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users:
    get:
      tags:
        - user
      summary: get-all
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /todo:
    get:
      tags:
        - todo
      summary: get-all-todo
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - todo
      summary: create-todo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                todo: lets goooo
                priority: low
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /todo/4:
    delete:
      tags:
        - todo
      summary: delete-todo
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - todo
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                todo: sssssssss
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
